version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: clickengine
      POSTGRES_USER: clickengine_user
      POSTGRES_PASSWORD: clickengine_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - clickengine-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - clickengine-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://clickengine_user:clickengine_password@postgres:5432/clickengine
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_here
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - clickengine-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: /api/v1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - clickengine-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - clickengine-network

volumes:
  postgres_data:
  redis_data:

networks:
  clickengine-network:
    driver: bridge